[oobe]
command = /etc/oobe.sh
defaultUid = 1000
defaultName = elementary OS WSL

[shortcut]
icon = /usr/lib/wsl/elementary-community.ico

[windowsterminal]
profileTemplate = /usr/lib/wsl/terminal-profile.json
